------------------TESTING------------------
DROP TABLE MENU_ITEM
UPDATE ACCOUNT SET PASSWORD = '123' WHERE NAME='online'
UPDATE MENU_ITEM SET NAME = N'newName' WHERE NAME='online'
DELETE FROM MENU_ITEM WHERE NAME = N'MH07'
SELECT COUNT(0) FROM MENU_ITEM
SELECT * FROM ORDERS WHERE TIME >='2022-11-04' AND TIME <='2022-11-05'

------------------REGENERATE MENU LIST----------------
USE DIMSUM
GO
DROP TABLE ORDER_DETAIL
DROP TABLE ORDERS
DROP TABLE MENU_ITEM
CREATE TABLE MENU_ITEM(
NAME NVARCHAR(50) NOT NULL PRIMARY KEY,
PRICE INT NOT NULL,
ENABLED BIT NOT NULL
)

INSERT INTO MENU_ITEM VALUES(N'Há cảo hấp',30000)
INSERT INTO MENU_ITEM VALUES(N'Há cảo chiên',30000)
INSERT INTO MENU_ITEM VALUES(N'Chân gà',28000)
INSERT INTO MENU_ITEM VALUES(N'Bánh cuốn tôm',40000)
INSERT INTO MENU_ITEM VALUES(N'Bánh tàu hủ',25000)
INSERT INTO MENU_ITEM VALUES(N'Xíu mại',30000)
INSERT INTO MENU_ITEM VALUES(N'Sườn kho',45000)
INSERT INTO MENU_ITEM VALUES(N'Bánh tôm chiên',50000)
INSERT INTO MENU_ITEM VALUES(N'Bánh trứng',20000)
INSERT INTO MENU_ITEM VALUES(N'Bánh dừa',42000)

CREATE TABLE ORDERS
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
TIME SMALLDATETIME NOT NULL
)

CREATE TABLE ORDER_DETAIL(
ID INT NOT NULL,
MENU_ITEM NVARCHAR(50) NOT NULL,
QUANTITY INT NOT NULL,
CONSTRAINT FK_ODD_MI FOREIGN KEY (MENU_ITEM) REFERENCES MENU_ITEM (NAME),
CONSTRAINT FK_ODD_ODS FOREIGN KEY (ID) REFERENCES ORDERS(ID)
)

------------------REGENERATE EXAMPLE ORDERS----------------


EXEC ADD_ORDER @ID=1,@MENU_ITEM=N'Bánh dừa',@QUANTITY=1,@TIME='2021-10-04 18:35:00'

EXEC ADD_ORDER @ID=2,@MENU_ITEM=N'Sườn kho',@QUANTITY=2,@TIME='2022-09-03 11:14:00'
EXEC ADD_ORDER @ID=2,@MENU_ITEM=N'Bánh dừa',@QUANTITY=4,@TIME='2022-10-01 08:11:00'

EXEC ADD_ORDER @ID=3,@MENU_ITEM=N'Sườn kho',@QUANTITY=2,@TIME='2022-10-04 10:50:00'
EXEC ADD_ORDER @ID=3,@MENU_ITEM=N'Bánh tàu hủ',@QUANTITY=1,@TIME='2022-11-02 19:31:00'

EXEC ADD_ORDER @ID=4,@MENU_ITEM=N'Bánh dừa',@QUANTITY=2,@TIME='2022-11-03 20:01:00'

EXEC ADD_ORDER @ID=5,@MENU_ITEM=N'Sườn kho',@QUANTITY=2,@TIME='2022-11-04 10:50:00'
EXEC ADD_ORDER @ID=5,@MENU_ITEM=N'Xíu mại',@QUANTITY=3,@TIME='2022-11-04 18:02:00'
EXEC ADD_ORDER @ID=5,@MENU_ITEM=N'Bánh dừa',@QUANTITY=1,@TIME='2022-11-04 21:43:00'


------------------TEMP----------------


