CREATE DATABASE DIMSUM
GO

USE DIMSUM
GO

CREATE TABLE TABLE_CODE(
CODE VARCHAR(5) NOT NULL
)
INSERT INTO TABLE_CODE VALUES('1234')
UPDATE TABLE_CODE SET CODE = '1234' WHERE CODE=(SELECT * FROM TABLE_CODE)

CREATE TABLE ACCOUNT(
NAME VARCHAR(50) NOT NULL primary key,
TYPE INT NOT NULL,
PASSWORD VARCHAR(100)NOT NULL,
CREATION_DATE DATE NOT NULL,
ENABLED BIT NOT NULL
)

INSERT INTO ACCOUNT VALUES('taikhoan1',1,'123','2020-01-01',1)
INSERT INTO ACCOUNT VALUES('taikhoan2',2,'123','2020-01-01',1)
INSERT INTO ACCOUNT VALUES('taikhoan3',3,'123','2020-01-01',1)

CREATE TABLE ACCOUNT_INFO(
ACCOUNT VARCHAR(50) NOT NULL PRIMARY KEY,
FULLNAME NVARCHAR(50) NOT NULL,
DATEOFBIRTH DATE NOT NULL,
GENDER VARCHAR(6) NOT NULL,
CONSTRAINT FK_ACI_AC FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT (NAME)
)

INSERT INTO ACCOUNT_INFO VALUES('taikhoan1',N'Danh Hồ','1994-01-01','MALE')
INSERT INTO ACCOUNT_INFO VALUES('taikhoan2',N'Nguyễn Thị B','1995-11-05','FEMALE')
INSERT INTO ACCOUNT_INFO VALUES('taikhoan3',N'Nguyễn Văn A','1980-11-03','MALE')

CREATE TABLE MENU_ITEM(
NAME NVARCHAR(50) NOT NULL PRIMARY KEY,
PRICE INT NOT NULL,
ENABLED BIT NOT NULL
)
INSERT INTO MENU_ITEM VALUES(N'Há cảo hấp',30000,1)
INSERT INTO MENU_ITEM VALUES(N'Há cảo chiên',30000,1)
INSERT INTO MENU_ITEM VALUES(N'Chân gà',28000,1)
INSERT INTO MENU_ITEM VALUES(N'Bánh cuốn tôm',40000,1)
INSERT INTO MENU_ITEM VALUES(N'Bánh tàu hủ',25000,1)
INSERT INTO MENU_ITEM VALUES(N'Xíu mại',30000,1)
INSERT INTO MENU_ITEM VALUES(N'Sườn kho',45000,1)
INSERT INTO MENU_ITEM VALUES(N'Bánh tôm chiên',50000,1)
INSERT INTO MENU_ITEM VALUES(N'Bánh trứng',20000,1)
INSERT INTO MENU_ITEM VALUES(N'Bánh dừa',42000,1)

CREATE TABLE ORDERS
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
TIME SMALLDATETIME NOT NULL,
TOTAL INT NOT NULL
)

CREATE TABLE ORDER_DETAIL(
ID INT NOT NULL,
MENU_ITEM NVARCHAR(50) NOT NULL,
QUANTITY INT NOT NULL,
CONSTRAINT FK_ODD_MI FOREIGN KEY (MENU_ITEM) REFERENCES MENU_ITEM (NAME),
CONSTRAINT FK_ODD_ODS FOREIGN KEY (ID) REFERENCES ORDERS(ID)
)
GO


CREATE PROC GET_NEXT_ORDER_ID
AS 
SELECT MAX(ID) FROM ORDERS
GO

CREATE VIEW ORDERS_DETAIL AS 
SELECT 
ORDERS.ID,
DETAIL.MENU_ITEM,
DETAIL.QUANTITY,
CONCAT(N'NGÀY ',DAY(ORDERS.TIME),'/',MONTH(ORDERS.TIME),'/',YEAR(ORDERS.TIME),': ',DATEPART(HH, ORDERS.TIME),N' GIỜ ',DATEPART(MI, ORDERS.TIME),N' PHÚT')AS 'FORMATED-TIME',
ORDERS.TIME, 
FORMAT(ORDERS.TOTAL,N'#,##0 "VNĐ"') AS 'TOTAL'
FROM ORDERS
INNER JOIN ORDER_DETAIL AS DETAIL 
ON ORDERS.ID = DETAIL.ID
GO

CREATE PROC DELETE_MENU_ITEM
@MENU_ITEM_NAME NVARCHAR(50)
AS
UPDATE MENU_ITEM SET ENABLED = '0' WHERE NAME = @MENU_ITEM_NAME
GO

CREATE PROC ADD_MENU_ITEM
@MENU_ITEM_NAME NVARCHAR(50),
@PRICE INT
AS
IF NOT((SELECT COUNT(*) FROM MENU_ITEM WHERE MENU_ITEM.NAME=@MENU_ITEM_NAME)=1)
INSERT INTO MENU_ITEM VALUES(@MENU_ITEM_NAME,@PRICE,1);
ELSE
BEGIN
UPDATE MENU_ITEM SET ENABLED = '1' WHERE NAME = @MENU_ITEM_NAME;
UPDATE MENU_ITEM SET PRICE = @PRICE WHERE NAME = @MENU_ITEM_NAME;
END;
GO


CREATE PROC CREATE_ORDER
@TIME SMALLDATETIME
AS 
INSERT INTO ORDERS VALUES(@TIME,0)
GO

CREATE PROC ADD_ORDER_ITEM
@ID INT,
@MENU_ITEM NVARCHAR(50),
@QUANTITY INT
AS
INSERT INTO ORDER_DETAIL VALUES(@ID,@MENU_ITEM,@QUANTITY)
GO



EXEC CREATE_ORDER @TIME='2021-10-04 18:35:00'
EXEC ADD_ORDER_ITEM @ID=1,@MENU_ITEM=N'Bánh dừa',@QUANTITY=1
UPDATE ORDERS SET TOTAL = '42000' WHERE ID = 1

EXEC CREATE_ORDER @TIME='2022-09-03 11:14:00'
EXEC ADD_ORDER_ITEM @ID=2,@MENU_ITEM=N'Sườn kho',@QUANTITY=2
EXEC ADD_ORDER_ITEM @ID=2,@MENU_ITEM=N'Bánh dừa',@QUANTITY=4
UPDATE ORDERS SET TOTAL = '258000' WHERE ID = 2

EXEC CREATE_ORDER @TIME='2022-10-04 10:50:00'
EXEC ADD_ORDER_ITEM @ID=3,@MENU_ITEM=N'Sườn kho',@QUANTITY=2
EXEC ADD_ORDER_ITEM @ID=3,@MENU_ITEM=N'Bánh tàu hủ',@QUANTITY=1
UPDATE ORDERS SET TOTAL = '115000' WHERE ID = 3

EXEC CREATE_ORDER @TIME='2022-11-03 20:01:00'
EXEC ADD_ORDER_ITEM @ID=4,@MENU_ITEM=N'Bánh dừa',@QUANTITY=2
UPDATE ORDERS SET TOTAL = '84000' WHERE ID = 4

EXEC CREATE_ORDER @TIME='2022-11-04 10:50:00'
EXEC ADD_ORDER_ITEM @ID=5,@MENU_ITEM=N'Sườn kho',@QUANTITY=2
EXEC ADD_ORDER_ITEM @ID=5,@MENU_ITEM=N'Xíu mại',@QUANTITY=3
EXEC ADD_ORDER_ITEM @ID=5,@MENU_ITEM=N'Bánh dừa',@QUANTITY=1
UPDATE ORDERS SET TOTAL = '222000' WHERE ID = 5
GO

CREATE PROC GET_DISTINCT_ORDER_DATES AS
WITH GROUPEDDATES 
AS
(SELECT SMALLDATETIMEFROMPARTS(YEAR(TIME),MONTH(TIME),DAY(TIME),0,0) as 'DATE'
FROM ORDERS 
GROUP BY SMALLDATETIMEFROMPARTS(YEAR(TIME),MONTH(TIME),DAY(TIME),0,0))
SELECT CONCAT(DAY(DATE),'/',MONTH(DATE),'/',YEAR(DATE))AS'DATE' FROM GROUPEDDATES
GO

CREATE PROC CHANGE_MENU_ITEM_NAME
@OLD_NAME NVARCHAR(50),
@NEW_NAME NVARCHAR(50)
AS
IF NOT((SELECT COUNT(*) FROM MENU_ITEM WHERE NAME=@NEW_NAME)=1)
BEGIN
ALTER TABLE ORDER_DETAIL DROP CONSTRAINT FK_ODD_MI
UPDATE MENU_ITEM SET NAME = @NEW_NAME WHERE NAME=@OLD_NAME
UPDATE ORDER_DETAIL SET MENU_ITEM = @NEW_NAME WHERE MENU_ITEM=@OLD_NAME
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ODD_MI FOREIGN KEY (MENU_ITEM) REFERENCES MENU_ITEM (NAME)
END
ELSE
BEGIN
UPDATE MENU_ITEM SET NAME = @NEW_NAME WHERE NAME=@OLD_NAME
END
GO

CREATE PROC CHANGE_ACCOUNT_INFO
@ACCOUNT VARCHAR(50),
@FULLNAME NVARCHAR(50),
@DATEOFBIRTH SMALLDATETIME,
@GENDER NVARCHAR(6)
AS
UPDATE ACCOUNT_INFO SET FULLNAME = @FULLNAME WHERE ACCOUNT_INFO.ACCOUNT = @ACCOUNT
UPDATE ACCOUNT_INFO SET DATEOFBIRTH = @DATEOFBIRTH WHERE ACCOUNT_INFO.ACCOUNT = @ACCOUNT
UPDATE ACCOUNT_INFO SET GENDER = @GENDER WHERE ACCOUNT_INFO.ACCOUNT = @ACCOUNT
GO

CREATE PROC ADD_ACCOUNT
@ACCOUNT VARCHAR(50),
@FULLNAME NVARCHAR(50),
@DATEOFBIRTH SMALLDATETIME,
@GENDER NVARCHAR(6)
AS
INSERT INTO ACCOUNT VALUES(@ACCOUNT,3,'123',CAST( GETDATE() AS Date ),0)
INSERT INTO ACCOUNT_INFO VALUES(@ACCOUNT,@FULLNAME,@DATEOFBIRTH,@GENDER)
GO

CREATE VIEW ACCOUNT_VIEW AS
SELECT ACCOUNT,FULLNAME,DATEOFBIRTH,GENDER,TYPE,CREATION_DATE,ENABLED FROM ACCOUNT
INNER JOIN ACCOUNT_INFO
ON ACCOUNT.NAME=ACCOUNT_INFO.ACCOUNT

